# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 09:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MenuItem',
            new_name='Item',
        ),
    ]
